### PR TITLE
change PrismaAdapter import

### PR DESCRIPTION
**Pull request by roy2554**
prevent `TypeError: _next_auth_prisma_adapter__WEBPACK_IMPORTED_MODULE_2___default(...) is not a function` error

### CODE REVIEW

**Comment by huv1k** [comment]
We should pin the version of the adapter, could you please do it? 🙏

**Comment by roy2554** [comment]
the adapter's version is 1.0.3
`"@next-auth/prisma-adapter": "^1.0.3"`

**Comment by huv1k** [comment]
Yea, could you please create a file `.npmrc` in root and add there `save-exact=true` like here https://github.com/huv1k/website/blob/master/.npmrc and then run `yarn add @next-auth/prisma-adapter` so we install the latest version and it's pinned to this exact version you mentioned? It would help a lot 🙌

**Comment by huv1k** [comment]
This was fixed in https://github.com/huv1k/nextjs-auth-prisma/pull/156

**Pull request closed without merging**
